# Utregning av integral ved hjelp av "sum" i numpy 

I dette notatet ser vi hvordan vi kan beregne integral nummerisk ved hjelp av å se på integral som Riemannsummer.
Vi tar eksempler i 1D og 2D.

Dette er for eksempel relevant for **[Ø1, O10] og [Ø2,O8]**


# 1D-eksempler

La oss si at funksjonen vår er $f(x)=\cos(x)$. Vi ønsker å regne ut $$\displaystyle{\int_R f(x)\; dx}$$ for 
$$ -1 \leq x < 1 .$$

## Numerisk bibliotek (Numpy = numerisk Python)

Vi gir en enkel numerisk metode hvor vi legger et gitter over integrasjonsområdet, regner ut funksjonsverdier og summerer. 

In [ ]:
import numpy as np


# Lengdeelementet


# Gitterpunkter


# Integrasjon


# print

In [ ]:
import numpy as np

# Lengdeelementet
dx = 0.000001

# Gitterpunkter
x = np.arange(-np.pi, np.pi, dx)

# Integrasjon
result = np.sum(np.cos(x)*dx)

print(result)

-6.936986640670995e-07


# 2D-eksempler
## Gittermetode med bruk av dobbel Riemannsum

Vi gir en enkel numerisk metode hvor vi legger et gitter over integrasjonsområdet, regner ut funksjonsverdier og summerer. 

### Kunsten å lage et gitter med Numpy:
For å lage et gitter bruker vi meshgrid, som forklart under.

In [ ]:
import numpy as np

x = [1, 2, 3,4,5]
y = [1, 2,3,4,5]

X, Y = np.meshgrid(x, y)

print("X =\n", X)
print("Y =\n", Y)
#print(X[0,0])
print(X[1,1],Y[1,1])

X =
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Y =
 [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
2 2


### Eksempel 1

 Vi regner ut $$\displaystyle{\iint_R x(1+y^3)\; dA}$$ for rektangelet 
$$R = \{(x,y)\in \mathbb{R}^2 | -1 \leq x < 1 \text{ og } 0 \leq y < 2\}.$$

In [ ]:
import numpy as np

# Arealelementet


# Gitterpunkter


# Integrasjon


# print

In [5]:
import numpy as np

xmin = -1.0
xmax = 1.0
ymin = 0.0
ymax = 2.0

numx = 1000
numy = 1000
dx = (xmax - xmin) / numx
dy = (ymax - ymin) / numy
dA = dx*dy

xv = np.linspace(xmin, xmax, numx, endpoint=False)
yv = np.linspace(ymin, ymax, numy, endpoint=False)
x, y = np.meshgrid(xv, yv)

svar = np.sum(x*(1+ y**3))*dA
print(svar)


-0.011984007999999737


Legg merke til hvor treigt det går om du forsøker å mine step-size. 

**Til ettertanke:** 
1. Hva er typen til x?
2. Hva er typen til X?
3. Hvorfor trenger jeg ikke lambda-def av funksjon her?



### Eksempel 2 (et lite triks)
La oss nå regne ut et eksempel: $$\displaystyle{\iint_D \sin(x+y)\; dA }$$ for den kvarte disken $D = \{(x,y)\in \mathbb{R}^2\; |\; x^2+y^2\leq 1, x\geq 0, y\geq 0\}$. Vi regner over et rektangel men ignorerer punkter som ligger utenfor disken.

In [6]:
import numpy as np

# Arealelementet
dx = 0.001
dy = 0.001
dA = dx*dy

# Gitteret
x = np.arange(0, 1, dx)
y = np.arange(0, 1, dy)
px,py = np.array(np.meshgrid(x,y))

# funksjonen
f = lambda x,y : np.sin(x+y) if x*x+y*y <= 1 else 0
f = np.vectorize(f)

# integrasjonen
result = np.sum(f(px,py)*dA) #Merk at denne summerer over hele meshgrid (så egentlig to nøstede summer)
print(result)

0.5626124066983764


### Forklaring av vectorize
I koden over brukte vi funksjonen "vectorize." Den gjør at en funksjon kan "ta inn vektorer (arrays)," altså regne ut en funksjonsverdi for mange forskjellige verdier som ligger lagret i en vector (array).

In [ ]:
import numpy as np

def myfunc(x):
    return x**2 + 1

data = np.array([1, 2, 3, 4])

# Skrive ut liste med data:
result = np.array([myfunc(x) for x in data])
print(result)  # [ 2  5 10 17 ]

vec_func = np.vectorize(myfunc)

result = vec_func(data)
print(result)  # [ 2  5 10 17 ]

[ 2  5 10 17]
<class 'numpy.ndarray'>
[ 2  5 10 17]
<class 'numpy.ndarray'>
