# Integrasjon i 2D med Python


# Gittermetode

Vi gir en enkel numerisk metode hvor vi legger et gitter over integrasjonsområdet, regner ut funksjonsverdier og summerer. 

La $f(x,y)=\cos(x\cdot y)$. Vi regner ut $$\displaystyle{\iint_R f(x,y)\; dA}$$ for rektangelet 
$$R = \{(x,y)\in \mathbb{R}^2 | -1 \leq x < 1 \text{ og } 0 \leq y < 2\}.$$

### Kunsten å lage et gitter med Numpy:
For å lage et gitter bruker vi meshgrid, som forklart under.

In [1]:
import numpy as np

x = [1, 2, 3,4,5]
y = [1, 2,3,4,5]

X, Y = np.meshgrid(x, y)

print("X =\n", X)
print("Y =\n", Y)
#print(X[0,0])
print(X[1,1],Y[1,1])

X =
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Y =
 [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
2 2


## Eksempel
La oss nå regne ut et eksempel: $$\displaystyle{\iint_D \sin(x+y)\; dA }$$ for den kvarte disken $D = \{(x,y)\in \mathbb{R}^2\; |\; x^2+y^2\leq 1, x\geq 0, y\geq 0\}$. Vi regner over et rektangel men ignorerer punkter som ligger utenfor disken.

In [3]:
import numpy as np

# Arealelementet
dx = 0.001
dy = 0.001
dA = dx*dy

# Gitteret
x = np.arange(0, 1, dx)
y = np.arange(0, 1, dy)
px,py = np.array(np.meshgrid(x,y))

# funksjonen
f = lambda x,y : np.sin(x+y) if x*x+y*y <= 1 else 0
f = np.vectorize(f)

# integrasjonen
result = np.sum(f(px,py)*dA)
print(result)

0.5626124066983763


### Forklaring av vectorize
I koden over brukte vi funksjonen "vectorize." Den gjør at en funksjon kan "ta inn vektorer (arrays)," altså regne ut en funksjonsverdi for mange forskjellige verdier som ligger lagret i en vector (array).

In [2]:
import numpy as np

def myfunc(x):
    return x**2 + 1

data = np.array([1, 2, 3, 4])

# Skrive ut liste med data:
result = np.array([myfunc(x) for x in data])
print(result)  # [ 2  5 10 17 ]

vec_func = np.vectorize(myfunc)

result = vec_func(data)
print(result)  # [ 2  5 10 17 ]

[ 2  5 10 17]
[ 2  5 10 17]


# Scipy for dobbelintegral

Utregning av integralet $$\displaystyle{\int_c^d\int_{a(x)}^{b(x)} f(x,y)\; dx\; dy}$$ kan også gjøres med Scipy sin funksjon quad. Funksjonen vi da bruker heter dblquad og er altså en høynivå funksjon. Den
* Benytter algoritmen QUADPACK, som er en adaptiv Gauss-Kronod kvadraturmetode (deler opp i små viter og evalurer funksjonen et sted på hver bit. 
* Stopper evalueringen når feilestimatet er under en gitt toleranseverdi
* `dblquad(f, a, b, gfun, hfun)` betyr:$$
\int_a^b \left( \int_{g(x)}^{h(x)} f(x,y)\, dy \right) dx
$$ Her er \(a = -1, \, b = 1\), og \(gfun = -1, \, hfun = 1\).


## Eksempel
La oss som eksempel regne ut integralet 

$$\int_0^1 \left( \int_x^{\sqrt{x}} x+y\, dy \right) dx$$

ved hjelp av Scipy:


In [4]:
import numpy as np
from scipy import integrate

f = lambda y, x : x*y
a = lambda x : x
b = lambda x : np.sqrt(x)
c = 0
d = 1

result = integrate.dblquad(f, c, d, a, b)

print(result)
print(type(result))
print(result[0], "er her integralet evaluert, mens") # value of the integral
print(result[1], "er feilestimatet") # estimate of error



(0.04166666666666667, 8.203240256944733e-16)
<class 'tuple'>
0.04166666666666667 er her integralet evaluert, mens
8.203240256944733e-16 er feilestimatet


# Et lite triks...

Det kan også være verdt å merke seg et lite numerisk triks vi kan benytte når vi bruker et dataverktøy som Python. Vi kan nemlig regne ved å integrere over større områder og forkaste verdier som ikke
skal brukes.

Her regner vi ut integralet $$\displaystyle{\iint_D x + y\; dA}$$ for disken $$D=\{(x,y)\in \mathbb{R}^2\; | \; x^2+y^2\leq 1\}.$$

Vi gjør dette ved å integrere over et rektangel som inneholder $D$, 
$$\displaystyle{\int_{-1}^1\int_{-1}^1 f(x,y)\; dA}$$
men definerer funksjonen $f$ lik $0$ utenfor disken. 


In [32]:
import numpy as np
from scipy import integrate

f = lambda x,y : x + y if x*x+y*y <= 1 else 0

result = integrate.dblquad(f, -1,1, -1,1)
print(result)

(0.0, 5.030565129848359e-08)
